spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  springdoc:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui
      operations-sorter: method
      enabled: true
      config-url: /api-docs/swagger-config
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
encryption:
  secret: ${ENCRYPTION_SECRET}